"""Bounded asynchronous key-value backends for RAG response caching."""

from __future__ import annotations

import asyncio
import time
from collections import OrderedDict
from collections.abc import Callable
from typing import Protocol


class AsyncKVCache(Protocol):
    """Minimal async byte-value cache contract used by the RAG pipeline.

    Implementations own their storage lifecycle and must preserve opaque keys
    and byte payloads. Backend errors are allowed to propagate from this port;
    :class:`docpipe.rag.pipeline.RAGPipeline` treats cache operations as
    best-effort and falls back to uncached query execution.
    """

    async def get(self, key: str) -> bytes | None:
        """Return bytes for a live key, or ``None`` when absent or expired.

        Raises:
            Exception: Backend-specific failures; callers decide whether a
                failed read is fatal or can be treated as a cache miss.
        """

    async def set(self, key: str, value: bytes, *, ttl_seconds: int) -> None:
        """Store a byte value with a finite lifetime.

        Args:
            key: Opaque key generated by the caller.
            value: Serialized cache payload.
            ttl_seconds: Positive lifetime in seconds.

        Raises:
            ValueError: If ``ttl_seconds`` is less than one.
            Exception: Backend-specific write failures.
        """

    async def close(self) -> None:
        """Release backend resources owned by this cache instance."""


class InMemoryKVCache:
    """Process-local bounded KV cache for development and single-worker use.

    This backend is intentionally not described as durable or distributed.
    Eviction is least-recently-used, and all entries have an explicit expiry.
    """

    def __init__(self, *, max_entries: int = 10_000, clock: Callable[[], float] = time.monotonic):
        """Create a bounded, process-local cache.

        Args:
            max_entries: Maximum number of live or not-yet-read entries retained.
                Least-recently-used entries are evicted when this bound is exceeded.
            clock: Monotonic clock used for expiration; injectable for deterministic
                tests.

        Raises:
            ValueError: If ``max_entries`` is less than one.

        Concurrent reads, writes, expiry checks, and eviction are serialized by
        an instance-local async lock. The cache is not shared across workers.
        """
        if max_entries < 1:
            raise ValueError("max_entries must be positive")
        self._max_entries = max_entries
        self._clock = clock
        self._entries: OrderedDict[str, tuple[float, bytes]] = OrderedDict()
        self._lock = asyncio.Lock()

    async def get(self, key: str) -> bytes | None:
        """Return a non-expired value and mark it most-recently used.

        Expired entries are removed when read. The operation is atomic relative
        to other operations on this cache instance.
        """
        async with self._lock:
            entry = self._entries.get(key)
            if entry is None:
                return None
            expires_at, value = entry
            if expires_at <= self._clock():
                del self._entries[key]
                return None
            self._entries.move_to_end(key)
            return value

    async def set(self, key: str, value: bytes, *, ttl_seconds: int) -> None:
        """Copy and store a value, evicting oldest entries to enforce the bound.

        Raises:
            ValueError: If ``ttl_seconds`` is less than one.
        """
        if ttl_seconds < 1:
            raise ValueError("ttl_seconds must be positive")
        async with self._lock:
            self._entries[key] = (self._clock() + ttl_seconds, bytes(value))
            self._entries.move_to_end(key)
            while len(self._entries) > self._max_entries:
                self._entries.popitem(last=False)

    async def close(self) -> None:
        """Clear cached answers when the owning application shuts down."""
        async with self._lock:
            self._entries.clear()


class RedisKVCache:
    """Optional Redis-backed TTL KV cache; Redis remains operator-managed.

    Construction is lazy with respect to network access so a temporary Redis
    outage does not prevent the API from starting. Call ``close`` at shutdown.
    """

    def __init__(self, client: object) -> None:
        """Wrap an async Redis-compatible client supplied by the caller.

        The caller owns client construction and connection policy, but this
        wrapper closes the supplied client or its pool from :meth:`close`.
        Treat wrapping as transferring shutdown responsibility: close the cache
        only after all users of a shared client have finished.
        """
        self._client = client

    @classmethod
    def from_url(cls, url: str, *, socket_timeout_seconds: float = 1.0) -> RedisKVCache:
        """Create a lazily connecting client using the optional Redis extra.

        Args:
            url: Redis URL, including operator-managed authentication and TLS
                settings as required by the deployment.
            socket_timeout_seconds: Connection and command timeout applied to
                the Redis client.

        Returns:
            A cache wrapper; this call does not establish a network connection.

        Raises:
            RuntimeError: If the optional ``redis`` package is not installed.
        """
        try:
            from redis.asyncio import Redis
        except ImportError as exc:
            raise RuntimeError(
                "Redis RAG caching requires the optional dependency; "
                "install docpipe-sdk[rag-redis]."
            ) from exc
        client = Redis.from_url(
            url,
            socket_connect_timeout=socket_timeout_seconds,
            socket_timeout=socket_timeout_seconds,
            decode_responses=False,
        )
        return cls(client)

    async def get(self, key: str) -> bytes | None:
        """Fetch one namespaced value, preserving Redis errors for the caller."""
        value = await self._client.get(_redis_key(key))  # type: ignore[attr-defined]
        return bytes(value) if value is not None else None

    async def set(self, key: str, value: bytes, *, ttl_seconds: int) -> None:
        """Write a namespaced value with Redis expiry in seconds.

        Raises:
            ValueError: If ``ttl_seconds`` is less than one.
            Exception: Redis client errors are propagated to the caller.
        """
        if ttl_seconds < 1:
            raise ValueError("ttl_seconds must be positive")
        await self._client.set(  # type: ignore[attr-defined]
            _redis_key(key), value, ex=ttl_seconds
        )

    async def close(self) -> None:
        """Close the async Redis client or pool owned by this wrapper."""
        close = getattr(self._client, "aclose", None) or self._client.close  # type: ignore[attr-defined]
        result = close()
        if asyncio.iscoroutine(result):
            await result


def _redis_key(key: str) -> str:
    """Add a stable namespace without retaining caller-controlled key text."""
    return f"docpipe:rag:{key}"
