apiVersion: v1
kind: Service
metadata:
  name: docpipe
  namespace: docpipe
  labels:
    app: docpipe
spec:
  type: ClusterIP
  selector:
    app: docpipe
  ports:
    - name: http
      port: 8000
      targetPort: 8000
