"""Public retrieval-augmented generation schemas."""

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, Field, field_validator, model_validator

from docpipe.config.plugin_options import VectorStoreOptions
from docpipe.core.schemas.common import TokenUsage, validate_table_name


class RAGConfig(BaseModel):
    """Configuration for the RAG query pipeline."""

    connection_string: str | None = Field(
        default=None, description="Legacy vector database connection URL; keep credentials secret."
    )
    table_name: str = Field(
        ..., description="Vector collection or table containing document chunks."
    )
    embedding_provider: str = Field(
        ..., description="Embedding provider registry name for query vectors."
    )
    embedding_model: str = Field(
        ..., description="Embedding model identifier compatible with indexed vectors."
    )
    embedding_api_key: str | None = Field(
        default=None, description="Optional embedding-provider credential; keep it secret."
    )
    llm_provider: str = Field(
        ..., description="Language-model provider registry name used to generate answers."
    )
    llm_model: str = Field(..., description="Language-model identifier used to generate answers.")
    llm_api_key: str | None = Field(
        default=None, description="Optional language-model credential; keep it secret."
    )
    strategy: Literal[
        "naive", "hyde", "multi_query", "parent_document", "hybrid", "auto", "lightrag"
    ] = Field(
        default="naive", description="Retrieval strategy used to find context for the answer."
    )
    lightrag_working_dir: str | None = Field(
        default=None, description="LightRAG graph-index directory when that strategy is selected."
    )
    top_k: int = Field(
        default=5, description="Number of candidate chunks requested from the vector store."
    )
    max_chunks_per_source: int = Field(
        default=2, description="Maximum retrieved chunks retained from one source document."
    )
    hyde_prompt: str | None = Field(
        default=None,
        description="Optional instruction used to generate a hypothetical answer for retrieval.",
    )
    multi_query_prompt: str | None = Field(
        default=None, description="Optional instruction for generating retrieval query variants."
    )
    auto_strategy_prompt: str | None = Field(
        default=None,
        description="Optional instruction for selecting a retrieval strategy automatically.",
    )
    multi_query_count: int = Field(
        default=3, description="Number of query variants generated by the multi-query strategy."
    )
    parent_window_size: int = Field(
        default=3, description="Number of neighboring chunks added around a matching child chunk."
    )
    hybrid_bm25_weight: float = Field(
        default=0.5,
        description="Relative keyword weight for hybrid retrieval where supported by the backend.",
    )
    reranker: Literal["none", "flashrank", "cohere", "bge", "mxbai"] = Field(
        default="none", description="Reranker plugin applied to retrieved candidate chunks."
    )
    reranker_model: str | None = Field(
        default=None,
        description="Optional model identifier overriding the reranker's default model.",
    )
    rerank_top_n: int | None = Field(
        default=None, description="Maximum number of chunks retained after reranking."
    )
    system_prompt: str | None = Field(
        default=None, description="System instruction used when generating the final answer."
    )
    history: list[dict[str, str]] = Field(
        default_factory=list,
        description="Prior conversation messages supplied as answer-generation context.",
    )
    output_model: Any = Field(
        default=None,
        description="Pydantic model class for structured RAG output",
        exclude=True,
    )
    response_format: dict[str, Any] | None = Field(
        default=None,
        description="JSON schema dict for structured output (REST-friendly)",
    )
    stream: bool = Field(
        default=False,
        description="Stream answer tokens as they are generated when supported by the caller.",
    )
    cache_enabled: bool = Field(
        default=False, description="Enable semantic answer caching for this pipeline instance."
    )
    cache_similarity_threshold: float = Field(
        default=0.95, description="Minimum query similarity required for a semantic cache hit."
    )
    cache_max_size: int = Field(
        default=100, description="Maximum number of answer entries retained by the in-memory cache."
    )
    filters: dict[str, Any] = Field(
        default_factory=dict, description="Metadata filters applied to vector-store retrieval."
    )
    vector_backend: Literal["pgvector", "turbovec"] | None = Field(
        default=None, description="Legacy vector-store backend selection."
    )
    vector_store: VectorStoreOptions | None = Field(
        default=None, description="Provider-neutral vector-store selection and settings."
    )
    turbovec_index_dir: str | None = Field(
        default=None, description="Filesystem directory containing the TurboVec index."
    )
    turbovec_bit_width: Literal[2, 3, 4] = Field(
        default=4, description="Quantization bit width for TurboVec vector storage."
    )

    _validate_table_name = field_validator("table_name")(validate_table_name)

    @model_validator(mode="after")
    def require_legacy_connection(self) -> RAGConfig:
        """Require the legacy DSN unless a namespaced provider is supplied."""
        if self.vector_store is None and not self.connection_string:
            raise ValueError("connection_string is required without vector_store")
        return self


class RAGChunk(BaseModel):
    """A single retrieved chunk with provenance."""

    content: str = Field(..., description="Text content retrieved from the source document.")
    score: float = Field(
        ..., description="Retrieval or reranker relevance score; its scale depends on the provider."
    )
    source: str = Field(..., description="Source identifier associated with this chunk.")
    page: int | None = Field(
        default=None, description="One-based source page number when available."
    )
    metadata: dict[str, Any] = Field(
        default_factory=dict, description="Additional indexed metadata associated with the chunk."
    )


class RAGResult(BaseModel):
    """Output of a RAGPipeline.query() call."""

    query: str = Field(..., description="Original user query submitted to the RAG pipeline.")
    answer: str = Field(..., description="Generated answer returned for the query.")
    strategy: str = Field(
        ..., description="Retrieval strategy used to assemble the answer context."
    )
    chunks: list[RAGChunk] = Field(..., description="Retrieved chunks used as answer context.")
    sources: list[str] = Field(
        ..., description="Distinct source identifiers represented in the retrieved chunks."
    )
    timing_seconds: float = Field(..., description="End-to-end query processing time in seconds.")
    usage: TokenUsage | None = Field(
        default=None,
        description="Token usage reported by the language-model provider, when available.",
    )
    structured: Any = Field(
        default=None,
        description="Parsed structured answer excluded from serialized output.",
        exclude=True,
    )
    metadata: dict[str, Any] = Field(
        default_factory=dict, description="Additional pipeline diagnostics and result metadata."
    )
